# Numpy를 이용해 텐서 만들기

In [1]:
import numpy as np

In [2]:
# 1차원 텐서 (벡터)
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [4]:
# 2차원 텐서 (행렬)
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [5]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


# PyTorch를 이용해 텐서 만들기

In [6]:
import torch

### 1차원 텐서

In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t, '\n')

print(t.dim())  # rank (차원)
print(t.shape)  # shape
print(t.size()) # shape

tensor([0., 1., 2., 3., 4., 5., 6.]) 

1
torch.Size([7])
torch.Size([7])


### 2차원 텐서

In [8]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t, '\n')

print(t.dim())  # rank
print(t.size()) # shape

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]) 

2
torch.Size([4, 3])


### 브로드캐스팅

In [9]:
# 두 행렬의 크기가 같을 때의 연산
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [10]:
# 두 텐서의 크기가 다를 때의 연산

# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [11]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # [[3, 3], [4, 4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 간단한 기능

### 행렬 곱셈과 원소 별 곱셈

In [12]:
# 행렬 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 * 2
print('Shape of Matrix 2: ', m2.shape) # 2 * 1
print(m1.matmul(m2)) # 2 * 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [13]:
# element-wise 곱셈 (브로드캐스팅이 된 후 수행)
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 평균

In [14]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [15]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [16]:
print(t.mean(dim=0)) # 첫번째 차원(행)을 제거한다

tensor([2., 3.])


In [17]:
print(t.mean(dim=1)) # 두번째 차원(열)을 제거한다
print(t.mean(dim=-1)) # 마지막 차원(열)을 제거한다

tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### 덧셈

In [18]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max와 ArgMax

In [19]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)


In [20]:
print(t.max(dim=0)) # 첫번째 차원(행) 제거

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


- 첫번째 열에서 3은 1번 인덱스
- 두번째 열에서 4는 1번 인덱스
- 다시 말해 3과 4의 인덱스는 [1, 1]

In [21]:
print('Max: ', t.max(dim=0)[0]) # 0번 인덱스 => max값
print('Argmax: ', t.max(dim=0)[1]) # 1번 인덱스 => argmax값

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [23]:
print(t.max(dim=1), '\n')
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1])) 

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
