# Numpy를 이용해 텐서 만들기

In [7]:
import numpy as np

In [2]:
# 1차원 텐서 (벡터)
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [4]:
# 2차원 텐서 (행렬)
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [5]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


# PyTorch를 이용해 텐서 만들기

In [8]:
import torch

### 1차원 텐서

In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t, '\n')

print(t.dim())  # rank (차원)
print(t.shape)  # shape
print(t.size()) # shape

tensor([0., 1., 2., 3., 4., 5., 6.]) 

1
torch.Size([7])
torch.Size([7])


### 2차원 텐서

In [ ]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t, '\n')

print(t.dim())  # rank
print(t.size()) # shape

### 브로드캐스팅

In [10]:
# 두 행렬의 크기가 같을 때의 연산
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [11]:
# 두 텐서의 크기가 다를 때의 연산

# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [12]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # [[3, 3], [4, 4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 간단한 기능

### 행렬 곱셈과 원소 별 곱셈

In [ ]:
# 행렬 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 * 2
print('Shape of Matrix 2: ', m2.shape) # 2 * 1
print(m1.matmul(m2)) # 2 * 1

In [ ]:
# element-wise 곱셈 (브로드캐스팅이 된 후 수행)
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

### 평균

In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())

In [13]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [14]:
print(t.mean(dim=0)) # 첫번째 차원(행)을 제거한다

tensor([2., 3.])


In [ ]:
print(t.mean(dim=1)) # 두번째 차원(열)을 제거한다
print(t.mean(dim=-1)) # 마지막 차원(열)을 제거한다