In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

지금까지처럼 직접 비용 함수를 정의하는 것이 아닌 파이토치에서 제공하는 함수를 사용해본다.

In [2]:
# model = nn.Linear(input_dim, output_dim)

In [3]:
# cost = F.mse_loss(presiction, y_train)

# 단순 선형 회귀
- y = 2x 로 가정 (W=2, b=0)

In [4]:
torch.manual_seed(1)

In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [6]:
model = nn.Linear(1,1) # input_dim=1, output_dim=1 (입력 x, 출력 y)

In [7]:
# model에 저장되어 있는 가중치 W와 편향 b
print(list(model.parameters())) # 첫번째 값 : W, 두번째 값 : b

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [8]:
# optimizer 설정. 경사 하강법 SGD를 사용, learning rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [9]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    # H(x)
    prediction = model(x_train)

    # cost
    cost = F.mse_loss(prediction, y_train) # PyTorch 제공 평균 제곱 오차 함수

    # cost로 H(x) 개선
    optimizer.zero_grad() # gradient 0으로 초기화
    # 비용함수 미분 -> gradient 계산
    cost.backward()
    # W, b update
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [10]:
# x에 임의의 값 4를 넣어 y값 확인
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var) # forwrd 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) 

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward>)


In [11]:
print(list(model.parameters())) # 학습 후 W와 b

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


- forward 연산 : H(x) 식의 입력 x로부터 예측된 y를 얻는 것
- 학습 전, prediction = model(x_train) => x_train으로부터 예측값을 리턴하는 forward 연산
- 학습 후, pred_y = model(new_var) => 임의의 값 new_var로부터 예측값을 리턴하는 forward 연산
- backward 연산 : 학습 과정에서 비용 함수를 미분해 기울기를 구하는 것
- cost.backward() : 비용 함수로부터 기울기를 구하는 backward 연산

# 다중 선형 회귀
- H(X) = w₁x₁ + w₂x₂ + w₃x₃ + b

In [12]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [13]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

In [14]:
print(list(model.parameters())) # w의 값이 3개임을 볼 수 있다.

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [15]:
# 학습률(learning rate) = 0.00001(1e-5)
# 학습률을 0.01로 설정할 경우 기울기가 발산
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [16]:
nb_epochs = 5000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()))

Epoch    0/5000 Cost: 42134.707031
Epoch  100/5000 Cost: 5.960090
Epoch  200/5000 Cost: 5.654707
Epoch  300/5000 Cost: 5.365413
Epoch  400/5000 Cost: 5.091413
Epoch  500/5000 Cost: 4.831860
Epoch  600/5000 Cost: 4.585968
Epoch  700/5000 Cost: 4.353065
Epoch  800/5000 Cost: 4.132451
Epoch  900/5000 Cost: 3.923481
Epoch 1000/5000 Cost: 3.725512
Epoch 1100/5000 Cost: 3.537961
Epoch 1200/5000 Cost: 3.360339
Epoch 1300/5000 Cost: 3.192072
Epoch 1400/5000 Cost: 3.032686
Epoch 1500/5000 Cost: 2.881712
Epoch 1600/5000 Cost: 2.738675
Epoch 1700/5000 Cost: 2.603187
Epoch 1800/5000 Cost: 2.474835
Epoch 1900/5000 Cost: 2.353291
Epoch 2000/5000 Cost: 2.238128
Epoch 2100/5000 Cost: 2.129045
Epoch 2200/5000 Cost: 2.025692
Epoch 2300/5000 Cost: 1.927799
Epoch 2400/5000 Cost: 1.835093
Epoch 2500/5000 Cost: 1.747250
Epoch 2600/5000 Cost: 1.664035
Epoch 2700/5000 Cost: 1.585215
Epoch 2800/5000 Cost: 1.510551
Epoch 2900/5000 Cost: 1.439824
Epoch 3000/5000 Cost: 1.372828
Epoch 3100/5000 Cost: 1.309343
Epoc

In [17]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.5621]], grad_fn=<AddmmBackward>)


In [18]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9836, 0.6775, 0.3494]], requires_grad=True), Parameter containing:
tensor([0.3578], requires_grad=True)]
